### ISSUE TITLE
Lightwave Integration stops working after HA restart.

### ISSUE THREAD

**Issue by ITHungry** [LightwaveSmartHome/homeassistant-lightwave-smart#1]
Hello,  Im having an issue with this intergration as follow:

Once intergration is working it runs fine untill ether another intergration needs updating or when updates are available for HA and i've applied the updates, the only way I can get it to run again is be disabling Eufy Hacs intergration, then rebooting HA and after a few mins it startworking.

Then I enable Eufy intergration and its fine untill the next updates and I have to follow the same course of action. 

Same strange if it is though, 

please find attached the Error logs
[home-assistant_lightwave_smart_2023-11-28T11-29-52.746Z.log](https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart/files/13487449/home-assistant_lightwave_smart_2023-11-28T11-29-52.746Z.log)

**Comment by ikb42** [comment]
I'll close this for now, please feel free to reopen if still and issue.
