### ISSUE TITLE
Cannot set brightness using custom component: set_brightness

### ISSUE THREAD

**Issue by RMMTSLLP** [LightwaveSmartHome/homeassistant-lightwave-smart#17]
Hi Guys, hoping someone can help I'm trying to set brightness using the Lightwave v2 (Smart Series) custom component: set_brightness using developer tools/actions.  Having set elent information  and hitting perform action I get error message "Failed to perform the action lightwave2.set_brightness. extra keys not allowed @ data['brightness']. Got None" 

My yaml =
action: lightwave2.set_brightness
data:
  brightness: 150
target:
  device_id: 053ee5a8dd47d7339b2dc7a11a7176e9

Any suggestions or is there an issue with this custom component.

Regards

Roger Morris

**Comment by RGarrett93** [comment]
It seems to be an issue with this custom component, it is giving me the same error.

**Comment by ikb42** [comment]
hi, see issue #12 
it should be fixed in this beta [v3.5.34-Beta](https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart/releases/tag/v3.5.34-Beta)
