### ISSUE TITLE
Resolve HVACMode warning for Lightwave climate entities

### ISSUE THREAD

**Issue by RGarrett93** [LightwaveSmartHome/homeassistant-lightwave-smart#21]
https://developers.home-assistant.io/blog/2024/01/24/climate-climateentityfeatures-expanded/

"  _As of Home Assistant Core 2024.2 we have added two new flags into ClimateEntityFeature: TURN_ON, TURN_OFF._

_Integrations implementing turn_on service call needs to set the TURN_ON feature flag. Integrations implementing turn_off service call needs to set the TURN_OFF feature flag._

_There will be a 10 month deprecation period (2025.1) where ClimateEntity will set these on behalf of the integrations implementing the respective methods and from 2025.1 it will make integrations unable to use the respective methods if entity features has not been set accordingly._

_Implementing the methods without setting the respective feature flag will create a warning log entry guiding the user to create an issue for the integration._ "

logger:
  default: warning
  logs:
Entity None (<class 'custom_components.lightwave_smart.climate.LWRF2Climate'>) implements HVACMode(s): heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart/issues?q=is%3Aopen+is%3Aissue

**Comment by xela1** [comment]
Have put this version on my dev system and confirmed the following:

1. HVACMode warnings no longer present
2. can operate lightwave devices from home assistant (lights, sockets, trvs) (extra testing on TRVs)
3. receiving state from lightwave
4. reconnect function seems to work better
5. multi press events detected by the event and on the smart switch pair attribute

No issues detected so far
