### ISSUE TITLE
Setting LED brightness

### ISSUE THREAD

**Issue by ianphillpott** [LightwaveSmartHome/homeassistant-lightwave-smart#8]
I might be being *really* dense, but I can't get the LED brightness to change using a service call.

It works fine using the slider in the GUI, but trying to automate their brightness doesn't seem to work (wanting them to go to 100% at night in the hall if motion detected to act as a sort of night light)

Does the lightwave_smart.set_brightness service call not work with the light.[name]_off_led_indcator ?? Or am I doing something wrong?

**Comment by ikb42** [comment]
Hello, hmm, I'm not sure, I'll give this a test hopefully next week.  In the meantime someone else may be able to shed some light.

**Comment by ikb42** [comment]
@ianphillpott it has been a while now, please re-open this if still an issue
